# Create a workflow that is triggered when a change is made to ./cmd/projects/create/**

name: Create Project - Build and Deploy
on:
  push:
    paths:
      - ".github/workflows/create-project.yaml"
      - "cmd/projects/create/main.go"
  workflow_dispatch:
    inputs:
      REASON:
        description: "Reason for running this workflow"
        required: true
        default: "Manual trigger"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: GOOS=linux GOARCH=amd64 go build -v -o ./out/create-project/main ./cmd/projects/create/main.go

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11

      - name: Terraform Init
        working-directory: infra/create_project
        run: terraform init

      - name: Terraform Plan
        working-directory: infra/create_project
        run: terraform plan -out=plan.out

      - name: Terraform Apply
        working-directory: infra/create_project
        run: terraform apply plan.out
